"""
Заполняет БД стартовым набором университетов — теми же 50 записями (id, name,
city, country, continent, cost, acceptance, gpa25/75, sat25/75, size, setting,
climate, research, cs, tags, aid), что зашиты в константе UNIVERSITIES в
unimatch-demo.html. Значения распарсены из самого фронтенд-файла, а не
перепечатаны вручную, чтобы цифры между фронтом и бэкендом не разъехались.

Запуск:  python3 seed_data.py
"""
from database import Base, engine, SessionLocal
import models

Base.metadata.create_all(bind=engine)

UNIVERSITIES = [
    dict(id=1, name='MIT', city='Cambridge', country='USA', continent='na', cost=57900, acceptance=0.04, gpa25=3.63, gpa75=3.98, sat25=1430, sat75=1580, size='Medium', setting='Urban', climate='Cold', research=5, cs=98, tags=['Elite CS', 'Research Powerhouse', 'Urban'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need, no merit aid'),
    dict(id=2, name='UC San Diego', city='San Diego', country='USA', continent='na', cost=34000, acceptance=0.24, gpa25=3.53, gpa75=3.88, sat25=1350, sat75=1500, size='Large', setting='Coastal', climate='Warm', research=4, cs=96, tags=['Strong CS', 'Near Ocean', 'Large'], aid_level='Medium', aid_merit=True, aid_note='Need-based aid + merit scholarships for out-of-state'),
    dict(id=3, name='University of Miami', city='Miami', country='USA', continent='na', cost=29000, acceptance=0.19, gpa25=3.56, gpa75=3.91, sat25=1370, sat75=1520, size='Medium', setting='Coastal', climate='Warm', research=3, cs=80, tags=['Coastal', 'Diverse', 'Private'], aid_level='Medium', aid_merit=True, aid_note='Generous merit scholarships available'),
    dict(id=4, name='USC', city='Los Angeles', country='USA', continent='na', cost=64000, acceptance=0.1, gpa25=3.6, gpa75=3.95, sat25=1410, sat75=1560, size='Large', setting='Urban', climate='Warm', research=4, cs=90, tags=['Strong CS', 'Urban', 'Alumni Network'], aid_level='High', aid_merit=True, aid_note='Strong need-based aid + Trustee/Presidential merit scholarships'),
    dict(id=5, name='Georgia Tech', city='Atlanta', country='USA', continent='na', cost=33000, acceptance=0.16, gpa25=3.57, gpa75=3.92, sat25=1390, sat75=1540, size='Large', setting='Urban', climate='Warm', research=5, cs=95, tags=['Top CS', 'Research', 'Public'], aid_level='Medium', aid_merit=True, aid_note='Merit scholarships; limited aid for international students'),
    dict(id=6, name='Arizona State University', city='Tempe', country='USA', continent='na', cost=29000, acceptance=0.88, gpa25=3.21, gpa75=3.56, sat25=1100, sat75=1250, size='Large', setting='Suburban', climate='Warm', research=3, cs=75, tags=['Accessible', 'Large', 'Innovation'], aid_level='Low', aid_merit=True, aid_note='Strong merit scholarships, limited need-based aid for international'),
    dict(id=7, name='University of Michigan', city='Ann Arbor', country='USA', continent='na', cost=53000, acceptance=0.18, gpa25=3.56, gpa75=3.91, sat25=1380, sat75=1530, size='Large', setting='Suburban', climate='Cold', research=5, cs=93, tags=['Top CS', 'Research', 'Big Campus'], aid_level='Medium', aid_merit=False, aid_note='Need-based aid, limited for international students'),
    dict(id=8, name='Carnegie Mellon', city='Pittsburgh', country='USA', continent='na', cost=60000, acceptance=0.11, gpa25=3.59, gpa75=3.94, sat25=1410, sat75=1560, size='Medium', setting='Urban', climate='Cold', research=5, cs=99, tags=['Elite CS', 'Research Powerhouse'], aid_level='Medium', aid_merit=False, aid_note='Need-based aid, highly competitive for international students'),
    dict(id=9, name='University of Toronto', city='Toronto', country='Canada', continent='na', cost=45000, acceptance=0.43, gpa25=3.44, gpa75=3.79, sat25=1280, sat75=1430, size='Large', setting='Urban', climate='Cold', research=5, cs=92, tags=['Top CS', 'Urban', 'International'], aid_level='Low', aid_merit=True, aid_note='Entrance scholarships; limited need-based aid for international'),
    dict(id=10, name='University of Waterloo', city='Waterloo', country='Canada', continent='na', cost=40000, acceptance=0.53, gpa25=3.38, gpa75=3.73, sat25=1240, sat75=1390, size='Medium', setting='Suburban', climate='Cold', research=4, cs=94, tags=['Co-op Program', 'Strong CS'], aid_level='Low', aid_merit=True, aid_note='Entrance scholarships based on admission average'),
    dict(id=11, name='University of British Columbia', city='Vancouver', country='Canada', continent='na', cost=38000, acceptance=0.52, gpa25=3.39, gpa75=3.74, sat25=1240, sat75=1390, size='Large', setting='Coastal', climate='Moderate', research=4, cs=87, tags=['Near Ocean', 'Scenic', 'Research'], aid_level='Low', aid_merit=True, aid_note='International Major Entrance Scholarship available'),
    dict(id=12, name='University of Edinburgh', city='Edinburgh', country='UK', continent='eu', cost=34000, acceptance=0.4, gpa25=3.45, gpa75=3.8, sat25=1290, sat75=1440, size='Large', setting='Urban', climate='Cold', research=4, cs=85, tags=['Historic', 'Urban', 'Research'], aid_level='Low', aid_merit=True, aid_note='A limited number of international merit scholarships'),
    dict(id=13, name='Imperial College London', city='London', country='UK', continent='eu', cost=45000, acceptance=0.15, gpa25=3.57, gpa75=3.92, sat25=1390, sat75=1540, size='Medium', setting='Urban', climate='Moderate', research=5, cs=96, tags=['Elite CS', 'Urban', 'STEM Focus'], aid_level='Medium', aid_merit=True, aid_note="President's scholarships for international students"),
    dict(id=14, name='TU Munich', city='Munich', country='Germany', continent='eu', cost=3000, acceptance=0.35, gpa25=3.48, gpa75=3.83, sat25=1310, sat75=1460, size='Large', setting='Urban', climate='Cold', research=5, cs=91, tags=['Low Cost', 'Research', 'Public'], aid_level='Low', aid_merit=False, aid_note='Tuition is already minimal, so aid need is low'),
    dict(id=15, name='TU Delft', city='Delft', country='Netherlands', continent='eu', cost=16000, acceptance=0.45, gpa25=3.42, gpa75=3.77, sat25=1270, sat75=1420, size='Medium', setting='Suburban', climate='Moderate', research=5, cs=89, tags=['Engineering Focus', 'Affordable'], aid_level='Medium', aid_merit=True, aid_note='Holland Scholarship available for non-EU students'),
    dict(id=16, name='ETH Zurich', city='Zurich', country='Switzerland', continent='eu', cost=1500, acceptance=0.27, gpa25=3.52, gpa75=3.87, sat25=1340, sat75=1490, size='Medium', setting='Urban', climate='Cold', research=5, cs=97, tags=['Elite CS', 'Low Cost', 'Research'], aid_level='Low', aid_merit=False, aid_note='Tuition already very low, scholarships are limited'),
    dict(id=17, name='NUS', city='Singapore', country='Singapore', continent='as', cost=28000, acceptance=0.2, gpa25=3.55, gpa75=3.9, sat25=1370, sat75=1520, size='Large', setting='Urban', climate='Warm', research=5, cs=94, tags=['Top CS', 'Urban', 'Asia Hub'], aid_level='Medium', aid_merit=True, aid_note='ASEAN & Science/Tech scholarships for international students'),
    dict(id=18, name='NTU Singapore', city='Singapore', country='Singapore', continent='as', cost=26000, acceptance=0.25, gpa25=3.53, gpa75=3.88, sat25=1350, sat75=1500, size='Large', setting='Suburban', climate='Warm', research=4, cs=90, tags=['Strong CS', 'Green Campus'], aid_level='Medium', aid_merit=True, aid_note='NTU international scholarships available'),
    dict(id=19, name='University of Tokyo', city='Tokyo', country='Japan', continent='as', cost=6000, acceptance=0.34, gpa25=3.48, gpa75=3.83, sat25=1310, sat75=1460, size='Large', setting='Urban', climate='Moderate', research=5, cs=88, tags=['Prestigious', 'Low Cost', 'Urban'], aid_level='Medium', aid_merit=True, aid_note='MEXT scholarships available (competitive)'),
    dict(id=20, name='KAIST', city='Daejeon', country='South Korea', continent='as', cost=5000, acceptance=0.15, gpa25=3.57, gpa75=3.92, sat25=1390, sat75=1540, size='Medium', setting='Suburban', climate='Cold', research=5, cs=93, tags=['Tech Focus', 'Research', 'Low Cost'], aid_level='High', aid_merit=True, aid_note='Most international students receive full tuition waivers'),
    dict(id=21, name='HKUST', city='Hong Kong', country='Hong Kong', continent='as', cost=19000, acceptance=0.13, gpa25=3.59, gpa75=3.94, sat25=1400, sat75=1550, size='Medium', setting='Coastal', climate='Warm', research=5, cs=92, tags=['Near Ocean', 'Elite CS'], aid_level='Medium', aid_merit=True, aid_note='Entrance scholarships for top international applicants'),
    dict(id=22, name='University of Melbourne', city='Melbourne', country='Australia', continent='oc', cost=35000, acceptance=0.7, gpa25=3.3, gpa75=3.65, sat25=1170, sat75=1320, size='Large', setting='Urban', climate='Moderate', research=4, cs=86, tags=['Urban', 'Research', 'Livable City'], aid_level='Medium', aid_merit=True, aid_note="Chancellor's scholarships for international students"),
    dict(id=23, name='University of Sydney', city='Sydney', country='Australia', continent='oc', cost=38000, acceptance=0.65, gpa25=3.32, gpa75=3.67, sat25=1190, sat75=1340, size='Large', setting='Coastal', climate='Warm', research=4, cs=83, tags=['Near Ocean', 'Urban'], aid_level='Medium', aid_merit=True, aid_note='International merit scholarships available'),
    dict(id=24, name='Australian National University', city='Canberra', country='Australia', continent='oc', cost=33000, acceptance=0.35, gpa25=3.48, gpa75=3.83, sat25=1310, sat75=1460, size='Medium', setting='Suburban', climate='Moderate', research=5, cs=85, tags=['Research', 'Small & Focused'], aid_level='Medium', aid_merit=True, aid_note="Chancellor's International Scholarship"),
    dict(id=25, name='Stanford University', city='Stanford', country='USA', continent='na', cost=62000, acceptance=0.04, gpa25=3.63, gpa75=3.98, sat25=1430, sat75=1580, size='Medium', setting='Suburban', climate='Warm', research=5, cs=99, tags=['Elite CS', 'Silicon Valley', 'Research Powerhouse'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need, no merit aid'),
    dict(id=26, name='UC Berkeley', city='Berkeley', country='USA', continent='na', cost=55000, acceptance=0.11, gpa25=3.59, gpa75=3.94, sat25=1410, sat75=1560, size='Large', setting='Urban', climate='Moderate', research=5, cs=98, tags=['Elite CS', 'Public Ivy', 'Research'], aid_level='Medium', aid_merit=False, aid_note='Need-based aid, limited for international students'),
    dict(id=27, name='Caltech', city='Pasadena', country='USA', continent='na', cost=60000, acceptance=0.03, gpa25=3.63, gpa75=3.98, sat25=1440, sat75=1590, size='Small', setting='Suburban', climate='Warm', research=5, cs=97, tags=['Elite STEM', 'Tiny & Intense', 'Research Powerhouse'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need, no merit aid'),
    dict(id=28, name='Cornell University', city='Ithaca', country='USA', continent='na', cost=66000, acceptance=0.07, gpa25=3.61, gpa75=3.96, sat25=1420, sat75=1570, size='Large', setting='Suburban', climate='Cold', research=5, cs=95, tags=['Ivy League', 'Strong CS', 'Research'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need'),
    dict(id=29, name='Princeton University', city='Princeton', country='USA', continent='na', cost=63000, acceptance=0.04, gpa25=3.63, gpa75=3.98, sat25=1430, sat75=1580, size='Medium', setting='Suburban', climate='Moderate', research=5, cs=96, tags=['Ivy League', 'Elite CS', 'Small Classes'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need, no loans'),
    dict(id=30, name='Columbia University', city='New York', country='USA', continent='na', cost=68000, acceptance=0.04, gpa25=3.63, gpa75=3.98, sat25=1430, sat75=1580, size='Medium', setting='Urban', climate='Cold', research=5, cs=94, tags=['Ivy League', 'Urban', 'Strong CS'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need'),
    dict(id=31, name='New York University', city='New York', country='USA', continent='na', cost=62000, acceptance=0.08, gpa25=3.61, gpa75=3.96, sat25=1420, sat75=1570, size='Large', setting='Urban', climate='Cold', research=4, cs=91, tags=['Urban', 'Strong CS', 'Global Campuses'], aid_level='Medium', aid_merit=True, aid_note='Need-based aid; some merit scholarships'),
    dict(id=32, name='Northwestern University', city='Evanston', country='USA', continent='na', cost=65000, acceptance=0.07, gpa25=3.61, gpa75=3.96, sat25=1420, sat75=1570, size='Medium', setting='Suburban', climate='Cold', research=5, cs=93, tags=['Strong CS', 'Research', 'Near Chicago'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need'),
    dict(id=33, name='Duke University', city='Durham', country='USA', continent='na', cost=64000, acceptance=0.06, gpa25=3.62, gpa75=3.97, sat25=1430, sat75=1580, size='Medium', setting='Suburban', climate='Warm', research=5, cs=92, tags=['Strong CS', 'Research', 'Small Classes'], aid_level='High', aid_merit=False, aid_note='Meets 100% of demonstrated need'),
    dict(id=34, name='Rice University', city='Houston', country='USA', continent='na', cost=58000, acceptance=0.09, gpa25=3.61, gpa75=3.96, sat25=1410, sat75=1560, size='Small', setting='Urban', climate='Warm', research=5, cs=92, tags=['Small & Focused', 'Strong CS', 'Research'], aid_level='High', aid_merit=True, aid_note='Generous need-based aid + some merit scholarships'),
    dict(id=35, name='University of Washington', city='Seattle', country='USA', continent='na', cost=40000, acceptance=0.45, gpa25=3.42, gpa75=3.77, sat25=1270, sat75=1420, size='Large', setting='Urban', climate='Moderate', research=5, cs=96, tags=['Top CS', 'Near Tech Industry', 'Public'], aid_level='Medium', aid_merit=False, aid_note='Need-based aid, limited for international students'),
    dict(id=36, name='University of Illinois Urbana-Champaign', city='Urbana-Champaign', country='USA', continent='na', cost=36000, acceptance=0.44, gpa25=3.43, gpa75=3.78, sat25=1270, sat75=1420, size='Large', setting='Suburban', climate='Cold', research=5, cs=97, tags=['Top CS', 'Research', 'Public'], aid_level='Low', aid_merit=True, aid_note='Merit scholarships; limited need-based aid for international'),
    dict(id=37, name='University of Texas at Austin', city='Austin', country='USA', continent='na', cost=40000, acceptance=0.29, gpa25=3.5, gpa75=3.85, sat25=1330, sat75=1480, size='Large', setting='Urban', climate='Warm', research=5, cs=94, tags=['Top CS', 'Urban', 'Public'], aid_level='Low', aid_merit=True, aid_note='Merit scholarships; limited need-based aid for international'),
    dict(id=38, name='Purdue University', city='West Lafayette', country='USA', continent='na', cost=30000, acceptance=0.53, gpa25=3.38, gpa75=3.73, sat25=1240, sat75=1390, size='Large', setting='Suburban', climate='Cold', research=4, cs=90, tags=['Strong CS', 'Engineering Focus', 'Public'], aid_level='Low', aid_merit=True, aid_note='Merit scholarships available'),
    dict(id=39, name='McGill University', city='Montreal', country='Canada', continent='na', cost=30000, acceptance=0.4, gpa25=3.45, gpa75=3.8, sat25=1290, sat75=1440, size='Large', setting='Urban', climate='Cold', research=4, cs=88, tags=['Historic', 'Urban', 'Research'], aid_level='Low', aid_merit=True, aid_note='Entrance scholarships; limited need-based aid for international'),
    dict(id=40, name='University of Cambridge', city='Cambridge', country='UK', continent='eu', cost=48000, acceptance=0.17, gpa25=3.57, gpa75=3.92, sat25=1380, sat75=1530, size='Medium', setting='Suburban', climate='Cold', research=5, cs=98, tags=['Elite CS', 'Historic', 'Research Powerhouse'], aid_level='Medium', aid_merit=True, aid_note='Cambridge Trust scholarships for international students'),
    dict(id=41, name='University of Oxford', city='Oxford', country='UK', continent='eu', cost=48000, acceptance=0.14, gpa25=3.58, gpa75=3.93, sat25=1390, sat75=1540, size='Medium', setting='Suburban', climate='Cold', research=5, cs=96, tags=['Elite', 'Historic', 'Research'], aid_level='Medium', aid_merit=True, aid_note='Reach Oxford & other scholarships for international students'),
    dict(id=42, name='EPFL', city='Lausanne', country='Switzerland', continent='eu', cost=2000, acceptance=0.18, gpa25=3.56, gpa75=3.91, sat25=1380, sat75=1530, size='Medium', setting='Suburban', climate='Moderate', research=5, cs=96, tags=['Elite CS', 'Low Cost', 'Research'], aid_level='Low', aid_merit=False, aid_note='Tuition already very low, scholarships are limited'),
    dict(id=43, name='KTH Royal Institute of Technology', city='Stockholm', country='Sweden', continent='eu', cost=18000, acceptance=0.35, gpa25=3.48, gpa75=3.83, sat25=1310, sat75=1460, size='Medium', setting='Urban', climate='Cold', research=4, cs=89, tags=['Strong CS', 'Affordable', 'Research'], aid_level='Medium', aid_merit=True, aid_note='KTH scholarships available for non-EU students'),
    dict(id=44, name='Tsinghua University', city='Beijing', country='China', continent='as', cost=5000, acceptance=0.02, gpa25=3.64, gpa75=3.99, sat25=1440, sat75=1590, size='Large', setting='Urban', climate='Cold', research=5, cs=97, tags=['Elite CS', 'Extremely Selective', 'Low Cost'], aid_level='High', aid_merit=True, aid_note='Chinese Government Scholarship covers most international admits'),
    dict(id=45, name='Seoul National University', city='Seoul', country='South Korea', continent='as', cost=6000, acceptance=0.1, gpa25=3.6, gpa75=3.95, sat25=1410, sat75=1560, size='Large', setting='Urban', climate='Cold', research=5, cs=92, tags=['Top CS', 'Low Cost', 'Research'], aid_level='Medium', aid_merit=True, aid_note='GKS scholarship available for international students'),
    dict(id=46, name='IIT Bombay', city='Mumbai', country='India', continent='as', cost=8000, acceptance=0.01, gpa25=3.65, gpa75=4.0, sat25=1440, sat75=1590, size='Medium', setting='Urban', climate='Warm', research=5, cs=93, tags=['Extremely Selective', 'Elite CS', 'Low Cost'], aid_level='Medium', aid_merit=True, aid_note='Merit-cum-means scholarships for eligible students'),
    dict(id=47, name='UNSW Sydney', city='Sydney', country='Australia', continent='oc', cost=37000, acceptance=0.6, gpa25=3.35, gpa75=3.7, sat25=1210, sat75=1360, size='Large', setting='Urban', climate='Warm', research=4, cs=87, tags=['Strong CS', 'Urban', 'Research'], aid_level='Medium', aid_merit=True, aid_note='International merit scholarships available'),
    dict(id=48, name='University of Auckland', city='Auckland', country='New Zealand', continent='oc', cost=28000, acceptance=0.55, gpa25=3.38, gpa75=3.73, sat25=1230, sat75=1380, size='Large', setting='Urban', climate='Moderate', research=3, cs=82, tags=['Top NZ University', 'Urban', 'Research'], aid_level='Medium', aid_merit=True, aid_note='International student scholarships available'),
    dict(id=49, name='University of São Paulo', city='São Paulo', country='Brazil', continent='sa', cost=2000, acceptance=0.15, gpa25=3.57, gpa75=3.92, sat25=1390, sat75=1540, size='Large', setting='Urban', climate='Warm', research=4, cs=85, tags=['Top Latin America', 'Low Cost', 'Research'], aid_level='Low', aid_merit=False, aid_note='Public university with minimal tuition; limited aid infrastructure for international students'),
    dict(id=50, name='University of Cape Town', city='Cape Town', country='South Africa', continent='af', cost=8000, acceptance=0.2, gpa25=3.55, gpa75=3.9, sat25=1370, sat75=1520, size='Large', setting='Urban', climate='Moderate', research=4, cs=83, tags=['Top Africa University', 'Research', 'Diverse'], aid_level='Medium', aid_merit=True, aid_note='International scholarships available for high-achieving students'),
]


def seed():
    db = SessionLocal()
    try:
        if db.query(models.University).count() > 0:
            print("Universities already seeded, skipping. Delete unimatch.db to reseed.")
            return
        for u in UNIVERSITIES:
            db.add(models.University(**u))
        db.commit()
        print(f"Seeded {len(UNIVERSITIES)} universities.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
