"""
Заполняет БД тем же набором из 50 университетов, что используется в demo-фронтенде,
чтобы можно было сразу проверить API с реалистичными данными.
Запуск: python seed_data.py
"""
from database import Base, engine, SessionLocal
import models

UNIVERSITIES = [
    dict(name="MIT", city="Cambridge", country="USA", continent="na", cost=57900, acceptance_rate=0.04, size="Medium", setting="Urban", climate="Cold", research_level=5, cs_strength=98, tags=["Elite CS","Research Powerhouse","Urban"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need, no merit aid"),
    dict(name="UC San Diego", city="San Diego", country="USA", continent="na", cost=34000, acceptance_rate=0.24, size="Large", setting="Coastal", climate="Warm", research_level=4, cs_strength=96, tags=["Strong CS","Near Ocean","Large"], aid_level="Medium", aid_merit=True, aid_note="Need-based aid + merit scholarships for out-of-state"),
    dict(name="University of Miami", city="Miami", country="USA", continent="na", cost=29000, acceptance_rate=0.19, size="Medium", setting="Coastal", climate="Warm", research_level=3, cs_strength=80, tags=["Coastal","Diverse","Private"], aid_level="Medium", aid_merit=True, aid_note="Generous merit scholarships available"),
    dict(name="USC", city="Los Angeles", country="USA", continent="na", cost=64000, acceptance_rate=0.1, size="Large", setting="Urban", climate="Warm", research_level=4, cs_strength=90, tags=["Strong CS","Urban","Alumni Network"], aid_level="High", aid_merit=True, aid_note="Strong need-based aid + Trustee/Presidential merit scholarships"),
    dict(name="Georgia Tech", city="Atlanta", country="USA", continent="na", cost=33000, acceptance_rate=0.16, size="Large", setting="Urban", climate="Warm", research_level=5, cs_strength=95, tags=["Top CS","Research","Public"], aid_level="Medium", aid_merit=True, aid_note="Merit scholarships; limited aid for international students"),
    dict(name="Arizona State University", city="Tempe", country="USA", continent="na", cost=29000, acceptance_rate=0.88, size="Large", setting="Suburban", climate="Warm", research_level=3, cs_strength=75, tags=["Accessible","Large","Innovation"], aid_level="Low", aid_merit=True, aid_note="Strong merit scholarships, limited need-based aid for international"),
    dict(name="University of Michigan", city="Ann Arbor", country="USA", continent="na", cost=53000, acceptance_rate=0.18, size="Large", setting="Suburban", climate="Cold", research_level=5, cs_strength=93, tags=["Top CS","Research","Big Campus"], aid_level="Medium", aid_merit=False, aid_note="Need-based aid, limited for international students"),
    dict(name="Carnegie Mellon", city="Pittsburgh", country="USA", continent="na", cost=60000, acceptance_rate=0.11, size="Medium", setting="Urban", climate="Cold", research_level=5, cs_strength=99, tags=["Elite CS","Research Powerhouse"], aid_level="Medium", aid_merit=False, aid_note="Need-based aid, highly competitive for international students"),
    dict(name="University of Toronto", city="Toronto", country="Canada", continent="na", cost=45000, acceptance_rate=0.43, size="Large", setting="Urban", climate="Cold", research_level=5, cs_strength=92, tags=["Top CS","Urban","International"], aid_level="Low", aid_merit=True, aid_note="Entrance scholarships; limited need-based aid for international"),
    dict(name="University of Waterloo", city="Waterloo", country="Canada", continent="na", cost=40000, acceptance_rate=0.53, size="Medium", setting="Suburban", climate="Cold", research_level=4, cs_strength=94, tags=["Co-op Program","Strong CS"], aid_level="Low", aid_merit=True, aid_note="Entrance scholarships based on admission average"),
    dict(name="University of British Columbia", city="Vancouver", country="Canada", continent="na", cost=38000, acceptance_rate=0.52, size="Large", setting="Coastal", climate="Moderate", research_level=4, cs_strength=87, tags=["Near Ocean","Scenic","Research"], aid_level="Low", aid_merit=True, aid_note="International Major Entrance Scholarship available"),
    dict(name="University of Edinburgh", city="Edinburgh", country="UK", continent="eu", cost=34000, acceptance_rate=0.4, size="Large", setting="Urban", climate="Cold", research_level=4, cs_strength=85, tags=["Historic","Urban","Research"], aid_level="Low", aid_merit=True, aid_note="A limited number of international merit scholarships"),
    dict(name="Imperial College London", city="London", country="UK", continent="eu", cost=45000, acceptance_rate=0.15, size="Medium", setting="Urban", climate="Moderate", research_level=5, cs_strength=96, tags=["Elite CS","Urban","STEM Focus"], aid_level="Medium", aid_merit=True, aid_note="President's scholarships for international students"),
    dict(name="TU Munich", city="Munich", country="Germany", continent="eu", cost=3000, acceptance_rate=0.35, size="Large", setting="Urban", climate="Cold", research_level=5, cs_strength=91, tags=["Low Cost","Research","Public"], aid_level="Low", aid_merit=False, aid_note="Tuition is already minimal, so aid need is low"),
    dict(name="TU Delft", city="Delft", country="Netherlands", continent="eu", cost=16000, acceptance_rate=0.45, size="Medium", setting="Suburban", climate="Moderate", research_level=5, cs_strength=89, tags=["Engineering Focus","Affordable"], aid_level="Medium", aid_merit=True, aid_note="Holland Scholarship available for non-EU students"),
    dict(name="ETH Zurich", city="Zurich", country="Switzerland", continent="eu", cost=1500, acceptance_rate=0.27, size="Medium", setting="Urban", climate="Cold", research_level=5, cs_strength=97, tags=["Elite CS","Low Cost","Research"], aid_level="Low", aid_merit=False, aid_note="Tuition already very low, scholarships are limited"),
    dict(name="NUS", city="Singapore", country="Singapore", continent="as", cost=28000, acceptance_rate=0.2, size="Large", setting="Urban", climate="Warm", research_level=5, cs_strength=94, tags=["Top CS","Urban","Asia Hub"], aid_level="Medium", aid_merit=True, aid_note="ASEAN & Science/Tech scholarships for international students"),
    dict(name="NTU Singapore", city="Singapore", country="Singapore", continent="as", cost=26000, acceptance_rate=0.25, size="Large", setting="Suburban", climate="Warm", research_level=4, cs_strength=90, tags=["Strong CS","Green Campus"], aid_level="Medium", aid_merit=True, aid_note="NTU international scholarships available"),
    dict(name="University of Tokyo", city="Tokyo", country="Japan", continent="as", cost=6000, acceptance_rate=0.34, size="Large", setting="Urban", climate="Moderate", research_level=5, cs_strength=88, tags=["Prestigious","Low Cost","Urban"], aid_level="Medium", aid_merit=True, aid_note="MEXT scholarships available (competitive)"),
    dict(name="KAIST", city="Daejeon", country="South Korea", continent="as", cost=5000, acceptance_rate=0.15, size="Medium", setting="Suburban", climate="Cold", research_level=5, cs_strength=93, tags=["Tech Focus","Research","Low Cost"], aid_level="High", aid_merit=True, aid_note="Most international students receive full tuition waivers"),
    dict(name="HKUST", city="Hong Kong", country="Hong Kong", continent="as", cost=19000, acceptance_rate=0.13, size="Medium", setting="Coastal", climate="Warm", research_level=5, cs_strength=92, tags=["Near Ocean","Elite CS"], aid_level="Medium", aid_merit=True, aid_note="Entrance scholarships for top international applicants"),
    dict(name="University of Melbourne", city="Melbourne", country="Australia", continent="oc", cost=35000, acceptance_rate=0.7, size="Large", setting="Urban", climate="Moderate", research_level=4, cs_strength=86, tags=["Urban","Research","Livable City"], aid_level="Medium", aid_merit=True, aid_note="Chancellor's scholarships for international students"),
    dict(name="University of Sydney", city="Sydney", country="Australia", continent="oc", cost=38000, acceptance_rate=0.65, size="Large", setting="Coastal", climate="Warm", research_level=4, cs_strength=83, tags=["Near Ocean","Urban"], aid_level="Medium", aid_merit=True, aid_note="International merit scholarships available"),
    dict(name="Australian National University", city="Canberra", country="Australia", continent="oc", cost=33000, acceptance_rate=0.35, size="Medium", setting="Suburban", climate="Moderate", research_level=5, cs_strength=85, tags=["Research","Small & Focused"], aid_level="Medium", aid_merit=True, aid_note="Chancellor's International Scholarship"),
    dict(name="Stanford University", city="Stanford", country="USA", continent="na", cost=62000, acceptance_rate=0.04, size="Medium", setting="Suburban", climate="Warm", research_level=5, cs_strength=99, tags=["Elite CS","Silicon Valley","Research Powerhouse"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need, no merit aid"),
    dict(name="UC Berkeley", city="Berkeley", country="USA", continent="na", cost=55000, acceptance_rate=0.11, size="Large", setting="Urban", climate="Moderate", research_level=5, cs_strength=98, tags=["Elite CS","Public Ivy","Research"], aid_level="Medium", aid_merit=False, aid_note="Need-based aid, limited for international students"),
    dict(name="Caltech", city="Pasadena", country="USA", continent="na", cost=60000, acceptance_rate=0.03, size="Small", setting="Suburban", climate="Warm", research_level=5, cs_strength=97, tags=["Elite STEM","Tiny & Intense","Research Powerhouse"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need, no merit aid"),
    dict(name="Cornell University", city="Ithaca", country="USA", continent="na", cost=66000, acceptance_rate=0.07, size="Large", setting="Suburban", climate="Cold", research_level=5, cs_strength=95, tags=["Ivy League","Strong CS","Research"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need"),
    dict(name="Princeton University", city="Princeton", country="USA", continent="na", cost=63000, acceptance_rate=0.04, size="Medium", setting="Suburban", climate="Moderate", research_level=5, cs_strength=96, tags=["Ivy League","Elite CS","Small Classes"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need, no loans"),
    dict(name="Columbia University", city="New York", country="USA", continent="na", cost=68000, acceptance_rate=0.04, size="Medium", setting="Urban", climate="Cold", research_level=5, cs_strength=94, tags=["Ivy League","Urban","Strong CS"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need"),
    dict(name="New York University", city="New York", country="USA", continent="na", cost=62000, acceptance_rate=0.08, size="Large", setting="Urban", climate="Cold", research_level=4, cs_strength=91, tags=["Urban","Strong CS","Global Campuses"], aid_level="Medium", aid_merit=True, aid_note="Need-based aid; some merit scholarships"),
    dict(name="Northwestern University", city="Evanston", country="USA", continent="na", cost=65000, acceptance_rate=0.07, size="Medium", setting="Suburban", climate="Cold", research_level=5, cs_strength=93, tags=["Strong CS","Research","Near Chicago"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need"),
    dict(name="Duke University", city="Durham", country="USA", continent="na", cost=64000, acceptance_rate=0.06, size="Medium", setting="Suburban", climate="Warm", research_level=5, cs_strength=92, tags=["Strong CS","Research","Small Classes"], aid_level="High", aid_merit=False, aid_note="Meets 100% of demonstrated need"),
    dict(name="Rice University", city="Houston", country="USA", continent="na", cost=58000, acceptance_rate=0.09, size="Small", setting="Urban", climate="Warm", research_level=5, cs_strength=92, tags=["Small & Focused","Strong CS","Research"], aid_level="High", aid_merit=True, aid_note="Generous need-based aid + some merit scholarships"),
    dict(name="University of Washington", city="Seattle", country="USA", continent="na", cost=40000, acceptance_rate=0.45, size="Large", setting="Urban", climate="Moderate", research_level=5, cs_strength=96, tags=["Top CS","Near Tech Industry","Public"], aid_level="Medium", aid_merit=False, aid_note="Need-based aid, limited for international students"),
    dict(name="University of Illinois Urbana-Champaign", city="Urbana-Champaign", country="USA", continent="na", cost=36000, acceptance_rate=0.44, size="Large", setting="Suburban", climate="Cold", research_level=5, cs_strength=97, tags=["Top CS","Research","Public"], aid_level="Low", aid_merit=True, aid_note="Merit scholarships; limited need-based aid for international"),
    dict(name="University of Texas at Austin", city="Austin", country="USA", continent="na", cost=40000, acceptance_rate=0.29, size="Large", setting="Urban", climate="Warm", research_level=5, cs_strength=94, tags=["Top CS","Urban","Public"], aid_level="Low", aid_merit=True, aid_note="Merit scholarships; limited need-based aid for international"),
    dict(name="Purdue University", city="West Lafayette", country="USA", continent="na", cost=30000, acceptance_rate=0.53, size="Large", setting="Suburban", climate="Cold", research_level=4, cs_strength=90, tags=["Strong CS","Engineering Focus","Public"], aid_level="Low", aid_merit=True, aid_note="Merit scholarships available"),
    dict(name="McGill University", city="Montreal", country="Canada", continent="na", cost=30000, acceptance_rate=0.4, size="Large", setting="Urban", climate="Cold", research_level=4, cs_strength=88, tags=["Historic","Urban","Research"], aid_level="Low", aid_merit=True, aid_note="Entrance scholarships; limited need-based aid for international"),
    dict(name="University of Cambridge", city="Cambridge", country="UK", continent="eu", cost=48000, acceptance_rate=0.17, size="Medium", setting="Suburban", climate="Cold", research_level=5, cs_strength=98, tags=["Elite CS","Historic","Research Powerhouse"], aid_level="Medium", aid_merit=True, aid_note="Cambridge Trust scholarships for international students"),
    dict(name="University of Oxford", city="Oxford", country="UK", continent="eu", cost=48000, acceptance_rate=0.14, size="Medium", setting="Suburban", climate="Cold", research_level=5, cs_strength=96, tags=["Elite","Historic","Research"], aid_level="Medium", aid_merit=True, aid_note="Reach Oxford & other scholarships for international students"),
    dict(name="EPFL", city="Lausanne", country="Switzerland", continent="eu", cost=2000, acceptance_rate=0.18, size="Medium", setting="Suburban", climate="Moderate", research_level=5, cs_strength=96, tags=["Elite CS","Low Cost","Research"], aid_level="Low", aid_merit=False, aid_note="Tuition already very low, scholarships are limited"),
    dict(name="KTH Royal Institute of Technology", city="Stockholm", country="Sweden", continent="eu", cost=18000, acceptance_rate=0.35, size="Medium", setting="Urban", climate="Cold", research_level=4, cs_strength=89, tags=["Strong CS","Affordable","Research"], aid_level="Medium", aid_merit=True, aid_note="KTH scholarships available for non-EU students"),
    dict(name="Tsinghua University", city="Beijing", country="China", continent="as", cost=5000, acceptance_rate=0.02, size="Large", setting="Urban", climate="Cold", research_level=5, cs_strength=97, tags=["Elite CS","Extremely Selective","Low Cost"], aid_level="High", aid_merit=True, aid_note="Chinese Government Scholarship covers most international admits"),
    dict(name="Seoul National University", city="Seoul", country="South Korea", continent="as", cost=6000, acceptance_rate=0.1, size="Large", setting="Urban", climate="Cold", research_level=5, cs_strength=92, tags=["Top CS","Low Cost","Research"], aid_level="Medium", aid_merit=True, aid_note="GKS scholarship available for international students"),
    dict(name="IIT Bombay", city="Mumbai", country="India", continent="as", cost=8000, acceptance_rate=0.01, size="Medium", setting="Urban", climate="Warm", research_level=5, cs_strength=93, tags=["Extremely Selective","Elite CS","Low Cost"], aid_level="Medium", aid_merit=True, aid_note="Merit-cum-means scholarships for eligible students"),
    dict(name="UNSW Sydney", city="Sydney", country="Australia", continent="oc", cost=37000, acceptance_rate=0.6, size="Large", setting="Urban", climate="Warm", research_level=4, cs_strength=87, tags=["Strong CS","Urban","Research"], aid_level="Medium", aid_merit=True, aid_note="International merit scholarships available"),
    dict(name="University of Auckland", city="Auckland", country="New Zealand", continent="oc", cost=28000, acceptance_rate=0.55, size="Large", setting="Urban", climate="Moderate", research_level=3, cs_strength=82, tags=["Top NZ University","Urban","Research"], aid_level="Medium", aid_merit=True, aid_note="International student scholarships available"),
    dict(name="University of São Paulo", city="São Paulo", country="Brazil", continent="sa", cost=2000, acceptance_rate=0.15, size="Large", setting="Urban", climate="Warm", research_level=4, cs_strength=85, tags=["Top Latin America","Low Cost","Research"], aid_level="Low", aid_merit=False, aid_note="Public university with minimal tuition; limited aid infrastructure for international students"),
    dict(name="University of Cape Town", city="Cape Town", country="South Africa", continent="af", cost=8000, acceptance_rate=0.2, size="Large", setting="Urban", climate="Moderate", research_level=4, cs_strength=83, tags=["Top Africa University","Research","Diverse"], aid_level="Medium", aid_merit=True, aid_note="International scholarships available for high-achieving students"),

]

if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    if db.query(models.University).count() == 0:
        db.bulk_insert_mappings(models.University, UNIVERSITIES)
        db.commit()
        print(f"Seeded {len(UNIVERSITIES)} universities.")
    else:
        print("Universities table already has data — skipping seed.")
    db.close()
